export const SUMOPOD_BASE_URL = 'https://api.sumopod.com/v1'

export const MODELS = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: 'Most capable multimodal model',
    supports_vision: true,
    badge: 'Popular',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    description: 'Fast & affordable GPT-4o variant',
    supports_vision: true,
    badge: 'Fast',
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    description: 'High capability with 128K context',
    supports_vision: true,
    badge: null,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    description: 'Fast and efficient for everyday tasks',
    supports_vision: false,
    badge: 'Lite',
  },
  {
    id: 'claude-3-5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: 'Best balance of intelligence & speed',
    supports_vision: true,
    badge: 'Smart',
  },
  {
    id: 'claude-3-5-haiku-20241022',
    name: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    description: 'Fastest Claude model',
    supports_vision: true,
    badge: 'Fast',
  },
  {
    id: 'claude-3-opus-20240229',
    name: 'Claude 3 Opus',
    provider: 'Anthropic',
    description: 'Most powerful Claude model',
    supports_vision: true,
    badge: 'Pro',
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    description: 'Long context up to 2M tokens',
    supports_vision: true,
    badge: null,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    description: 'Fast and versatile multimodal',
    supports_vision: true,
    badge: 'Fast',
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    description: 'Next-gen multimodal intelligence',
    supports_vision: true,
    badge: 'New',
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'DeepSeek',
    description: 'Powerful reasoning & coding model',
    supports_vision: false,
    badge: null,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    description: 'Advanced reasoning model',
    supports_vision: false,
    badge: 'Reason',
  },
  {
    id: 'llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    description: 'Open source powerhouse',
    supports_vision: false,
    badge: 'Open',
  },
  {
    id: 'llama-3.2-90b-vision-instruct',
    name: 'Llama 3.2 90B Vision',
    provider: 'Meta',
    description: 'Large multimodal open model',
    supports_vision: true,
    badge: 'Open',
  },
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    provider: 'Mistral',
    description: 'Top-tier multilingual reasoning',
    supports_vision: false,
    badge: null,
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral Nemo',
    provider: 'Mistral',
    description: 'Efficient & fast multilingual',
    supports_vision: false,
    badge: 'Lite',
  },
]

export const PROVIDER_COLORS = {
  OpenAI: { from: '#10b981', to: '#059669' },
  Anthropic: { from: '#f59e0b', to: '#d97706' },
  Google: { from: '#60a5fa', to: '#3b82f6' },
  DeepSeek: { from: '#8b5cf6', to: '#7c3aed' },
  Meta: { from: '#f97316', to: '#ea580c' },
  Mistral: { from: '#ec4899', to: '#db2777' },
}
